server:
  port: 8090

spring:
  application:
    name: COMMANDE-SERVICE
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost/commandems?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: phpmyadmin
    password: root 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false
      